name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env: 
  GOOGLE_APPLICATION_CREDENTIALS: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
  ARTIFACT_REPO: polygonio-news-sentiment-repo
  GCP_ZONE: us-central1
  IMAGE_NAME: polygonio-news-sentiment-data

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        project_id: ${{ secrets.PROJECT_ID }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker $GCP_ZONE-docker.pkg.dev

    # Build the Docker image
    - name: Build
      run: |-
        echo "${{secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > ./google.json
        docker build \
          --tag "$GCP_ZONE-docker.pkg.dev$PROJECT_ID/$ARTIFACT_REPO/$IMAGE_NAME:$GITHUB_SHA" \
          .

    # Push image to Google Container Registry
    - name: Push
      run: |-
        docker push $GCP_ZONE-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPO/$IMAGE_NAME:$GITHUB_SHA
